- name: Deploy Beacon DNS
  hosts: all
  tasks:
    - name: Install required packages
      apt:
        name:
          - python3
        state: present
        update_cache: yes

    - name: Copy binary
      copy:
        src: ../../beacon
        dest: /usr/local/bin/
        mode: "0755"

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: "0750"
      loop:
        - /var/lib/beacon/

    - name: Create files
      file:
        path: "{{ item }}"
        state: touch
        mode: "0644"
      loop:
        - /run/beacon.pid
        - /var/lib/beacon/config.yml
        - /var/lib/beacon/beacon.log

    - name: Create environment file
      copy:
        content: |
          BEACON_CONFIG_FILE=/var/lib/beacon/config.yml
          BEACON_DATA_DIR=/var/lib/beacon
        dest: /var/lib/beacon/.env
        mode: "0600"

    - name: Install systemd service file
      copy:
        content: |
          [Unit]
          Description=Beacon DNS Service
          After=network.target

          [Service]
          EnvironmentFile=/var/lib/beacon/.env
          ExecStart=/usr/local/bin/beacon
          WorkingDirectory=/var/lib/beacon
          User=root
          PIDFile=/run/beacon.pid
          StandardOutput=append:/var/lib/beacon/beacon.log
          StandardError=append:/var/lib/beacon/beacon.log
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/beacon.service
        mode: "0644"

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start beacon service
      systemd:
        name: beacon
        enabled: yes
        state: restarted
