- name: Deploy Beacon DNS
  hosts: all
  tasks:
    - name: Install required packages
      apt:
        name:
          - python3
        state: present
        update_cache: yes

    - name: Copy binary
      copy:
        src: ../../beacon
        dest: /usr/local/bin/
        mode: "0755"

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: "0750"
      loop:
        - /var/lib/beacon/

    - name: Create files
      file:
        path: "{{ item }}"
        state: touch
        mode: "0644"
      loop:
        - /run/beacon.pid
        - /var/lib/beacon/beacon.log

    - name: Create environment file
      copy:
        content: |
          BEACON_CONFIG_FILE=/var/lib/beacon/config.yml
          BEACON_DATA_DIR=/var/lib/beacon
        dest: /var/lib/beacon/.env
        mode: "0600"

    - name: Create configuration file
      copy:
        content: |
          system:
            timezone: Africa/Nairobi

          dns:
            port: 53
            upstreams:
              - 1.1.1.1
              - 8.8.8.8

          cache:
            capacity: 10000
            serve_stale:
              for: 5m
              with_ttl: 15s
            access_patterns:
              follow: true
              look_back: 14d

          api:
            port: 80

          client_lookup:
            upstream: 100.100.100.100
            method: tailscale

          groups:
            all:
              block:
                - ads
                - malware
                - adult

            screens:
              devices:
                - phone
                - terra
                - tv

          schedules:
            focus:
              apply_to:
                - screens
              when:
                - days: ["mon", "tue", "wed", "thur", "fri"]
                  periods:
                    - start: "09:00"
                      end: "18:00"
              block:
                - social-media
                - video-streaming
                - gaming
                - dating

            bedtime:
              apply_to:
                - screens
              when:
                - days: ["sun", "mon", "tue", "wed", "thur", "fri", "sat"]
                  periods:
                    - start: "22:00"
                      end: "06:00"
              block:
                - social-media
                - video-streaming
                - gaming
                - dating

          querylog:
            enabled: true
            log_clients: true
            retention: 90d

          sources:
            update_interval: 1d
        dest: /var/lib/beacon/config.yml
        mode: "0600"

    - name: Install systemd service file
      copy:
        content: |
          [Unit]
          Description=Beacon DNS Service
          After=network.target

          [Service]
          EnvironmentFile=/var/lib/beacon/.env
          ExecStart=/usr/local/bin/beacon
          WorkingDirectory=/var/lib/beacon
          User=root
          PIDFile=/run/beacon.pid
          StandardOutput=file:/var/lib/beacon/beacon.log
          StandardError=file:/var/lib/beacon/beacon.log
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/beacon.service
        mode: "0644"

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start beacon service
      systemd:
        name: beacon
        enabled: yes
        state: restarted
