kernel:
  image: linuxkit/kernel:6.6.13
  cmdline: "console=ttyS0"

init:
  - linuxkit/init:e120ea2a30d906bd1ee1874973d6e4b1403b5ca3
  - linuxkit/runc:6062483d748609d505f2bcde4e52ee64a3329f5f
  - linuxkit/containerd:39301e7312f13eedf19bd5d5551af7b37001d435
  - linuxkit/ca-certificates:5aaa343474e5ac3ac01f8b917e82efb1063d80ff

onboot:
  - name: sysctl
    image: linuxkit/sysctl:5a374e4bf3e5a7deeacff6571d0f30f7ea8f56db

  - name: dhcpcd
    image: linuxkit/dhcpcd:e9e3580f2de00e73e7b316a007186d22fea056ee
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]

  - name: metadata
    image: linuxkit/metadata:b082f1bf97a9034d1e4c0e36a5d2923f4e58f540
    command: ["/usr/bin/metadata", "vultr"]

services:
  - name: getty
    image: linuxkit/getty:5d86a2ce2d890c14ab66b13638dcadf74f29218b
    env:
     - INSECURE=true

  - name: rngd
    image: linuxkit/rngd:83a6481f04da73e710c1d416355920b8ff4dc1dd

  - name: sshd
    image: linuxkit/sshd:75f399fbfb6455dfccd4cb30543d0b4b494d28c8
    binds.add:
     - /run/config/ssh/authorized_keys:/root/.ssh/authorized_keys

  - name: beacon-dns
    image: st3v3nmw/beacon-dns:latest
    capabilities:
      - CAP_NET_BIND_SERVICE
    net: host
    binds:
      - /beacon-dns-data:/beacon-dns-data
    env:
      - BEACON_API_PORT=${BEACON_API_PORT}
      - BEACON_DNS_PORT=${BEACON_DNS_PORT}
      - BEACON_DATA_DIR=/beacon-dns-data
      - BEACON_BUCKET_NAME=${BEACON_BUCKET_NAME}
      - BEACON_BUCKET_KEY_ID=${BEACON_BUCKET_KEY_ID}
      - BEACON_BUCKET_KEY=${BEACON_BUCKET_KEY}
      - BEACON_BUCKET_ENDPOINT=${BEACON_BUCKET_ENDPOINT}
      - BEACON_BUCKET_REGION=${BEACON_BUCKET_REGION}

volumes:
- name: beacon-dns-data
