services:
  beacon-dns:
    container_name: beacon-dns
    image: ghcr.io/st3v3nmw/beacon-dns:latest
    volumes:
      - /home/${USER}/beacon-dns:/data
    environment:
      - BEACON_CONFIG_FILE=/data/config.yml
      - BEACON_DATA_DIR=/data
      - BEACON_EXTENSIONS_DIR=/extensions
    restart: unless-stopped
    privileged: true
    network_mode: host
